[package]
name = "buildscript"
version = "0.1.0"
edition = "2024"

[target.'cfg(unix)'.dependencies]
flate2 = "1.1.2"
tar = "0.4.44"
xz = "0.1.0"

[dependencies]
# bzip2 = "0.6.0"
dotenvy = "0.15.7"
ureq = "3.0.12"
